/**
 * The shared vocabulary of the product.
 *
 * Both apps render the same statuses, so the labels, colours and ordering live
 * here rather than being retyped per screen. Keys are stable strings written to
 * Firestore; the Spanish text is presentation only and safe to reword.
 */

/* --- Delivery ------------------------------------------------------------- */

/** The happy path, in order. `progress` drives the tracking timeline. */
export const DELIVERY_FLOW = ['scheduled', 'preparing', 'en_route', 'delivered'];

export const DELIVERY = {
  scheduled:  { label: 'Programado',   short: 'Programado', tone: 'info',  icon: 'calendar', clientText: 'Tu comida está programada para hoy.' },
  preparing:  { label: 'En cocina',    short: 'En cocina',  tone: 'warn',  icon: 'utensils', clientText: 'Estamos preparando tu comida.' },
  en_route:   { label: 'En camino',    short: 'En camino',  tone: 'brand', icon: 'truck',    clientText: 'Tu comida va en camino al rancho.' },
  delivered:  { label: 'Entregado',    short: 'Entregado',  tone: 'ok',    icon: 'check',    clientText: 'Tu comida fue entregada.' },
  skipped:    { label: 'Sin servicio', short: 'Sin serv.',  tone: 'muted', icon: 'ban',      clientText: 'Hoy no hay servicio programado.' },
  issue:      { label: 'Con problema', short: 'Problema',   tone: 'bad',   icon: 'alert',    clientText: 'Hubo un problema con la entrega de hoy.' },
};

export const deliveryMeta = (status) => DELIVERY[status] || DELIVERY.scheduled;

/** How far along the flow a status sits; -1 for statuses outside it. */
export const deliveryProgress = (status) => DELIVERY_FLOW.indexOf(status);

/** The next step a driver would tap, or null at the end of the flow. */
export function nextDeliveryStatus(status) {
  const at = DELIVERY_FLOW.indexOf(status);
  if (at < 0 || at === DELIVERY_FLOW.length - 1) return null;
  return DELIVERY_FLOW[at + 1];
}

export const ADVANCE_LABEL = {
  scheduled: 'Iniciar cocina',
  preparing: 'Salir a ruta',
  en_route: 'Marcar entregado',
};

/* --- Client --------------------------------------------------------------- */

export const CLIENT_STATUS = {
  active: { label: 'Activo',    tone: 'ok',    icon: 'check' },
  paused: { label: 'En pausa',  tone: 'warn',  icon: 'pause' },
  inactive: { label: 'Inactivo', tone: 'muted', icon: 'ban' },
};

export const clientStatusMeta = (status) => CLIENT_STATUS[status] || CLIENT_STATUS.active;

/* --- Payments ------------------------------------------------------------- */

export const PAYMENT_METHODS = {
  cash:     { label: 'Efectivo',       icon: 'cash' },
  transfer: { label: 'Transferencia',  icon: 'card' },
  cheque:   { label: 'Cheque',         icon: 'note' },
  card:     { label: 'Tarjeta',        icon: 'card' },
  other:    { label: 'Otro',           icon: 'wallet' },
};

export const paymentMethodMeta = (method) => PAYMENT_METHODS[method] || PAYMENT_METHODS.other;

/* --- Roles ---------------------------------------------------------------- */

export const ROLE = { admin: 'admin', client: 'client' };

/* --- Message kinds -------------------------------------------------------- */

export const MESSAGE_KIND = {
  text: 'text',
  system: 'system',      // generated by the app (payment recorded, delivery issue…)
  payment: 'payment',    // a payment-details request or confirmation
};

/** Canned openers, so a farm manager never has to compose from scratch. */
export const CLIENT_QUICK_REPLIES = [
  '¿Me pueden enviar los datos para el pago?',
  '¿A qué hora llega la comida hoy?',
  'Necesito cambiar el número de comidas.',
  'Hoy no habrá servicio en el rancho.',
  'Tuvimos un problema con la entrega.',
];

export const ADMIN_QUICK_REPLIES = [
  'Buen día, ya salió su pedido.',
  'Los datos para el pago son:',
  'Confirmamos su pago, gracias.',
  '¿Cuántas comidas necesitan mañana?',
  'Hoy vamos con retraso, disculpe la demora.',
];

/* --- Tone -> CSS ---------------------------------------------------------- */

export const badgeClass = (tone) => (tone && tone !== 'muted' ? `badge badge--${tone}` : 'badge');
export const dotClass   = (tone) => (tone && tone !== 'muted' ? `dot dot--${tone}` : 'dot');
export const stripeClass = (tone) => (tone && tone !== 'muted' ? `stripe stripe--${tone}` : 'stripe');
