/**
 * The shared vocabulary of the product.
 *
 * Both apps render the same statuses, so the labels, colours and ordering live
 * here rather than being retyped per screen. Keys are stable strings written to
 * Firestore; the Spanish text is presentation only and safe to reword.
 */

/* --- Client --------------------------------------------------------------- */

export const CLIENT_STATUS = {
  active: { label: 'Activo',    tone: 'ok',    icon: 'check' },
  paused: { label: 'En pausa',  tone: 'warn',  icon: 'pause' },
  inactive: { label: 'Inactivo', tone: 'muted', icon: 'ban' },
};

export const clientStatusMeta = (status) => CLIENT_STATUS[status] || CLIENT_STATUS.active;

/* --- Payments ------------------------------------------------------------- */

export const PAYMENT_METHODS = {
  cash:     { label: 'Efectivo',       icon: 'cash' },
  transfer: { label: 'Transferencia',  icon: 'card' },
  cheque:   { label: 'Cheque',         icon: 'note' },
  card:     { label: 'Tarjeta',        icon: 'card' },
  other:    { label: 'Otro',           icon: 'wallet' },
};

export const paymentMethodMeta = (method) => PAYMENT_METHODS[method] || PAYMENT_METHODS.other;

/* --- Roles ---------------------------------------------------------------- */

export const ROLE = { admin: 'admin', client: 'client' };

/* --- Message kinds -------------------------------------------------------- */

export const MESSAGE_KIND = {
  text: 'text',
  system: 'system',      // generated by the app (payment recorded, delivery issue…)
  payment: 'payment',    // a payment-details request or confirmation
};

/** Canned openers, so nobody has to compose a message from scratch. */
export const CLIENT_QUICK_REPLIES = [
  '¿Me pueden enviar los datos para el pago?',
  '¿Cuánto debo?',
  'Necesito cambiar el número de comidas.',
  'Voy a pasar a pagar hoy.',
  'Tuve un problema con mi comida.',
];

export const ADMIN_QUICK_REPLIES = [
  'Buen día, le recordamos su pago pendiente.',
  'Los datos para el pago son:',
  'Confirmamos su pago, gracias.',
  '¿Cuántas comidas necesita el próximo periodo?',
  'Puede pasar a la cocina cuando guste.',
];

/* --- Tone -> CSS ---------------------------------------------------------- */

export const badgeClass = (tone) => (tone && tone !== 'muted' ? `badge badge--${tone}` : 'badge');
export const dotClass   = (tone) => (tone && tone !== 'muted' ? `dot dot--${tone}` : 'dot');
export const stripeClass = (tone) => (tone && tone !== 'muted' ? `stripe stripe--${tone}` : 'stripe');
